- title: "AI Strategy & Roadmap"
  description: "Develop comprehensive AI strategies aligned with your business objectives. From assessment to implementation planning, I help you chart the right course for digital transformation."
  order: 1

- title: "ATPM Implementation"
  description: "Transform your development process with ATPM (Assessment, Testing, Program, Management) methodology for reliable, maintainable AI solutions with 40% faster delivery."
  order: 2

- title: "PRD-Centered Development"
  description: "Implement PRD-centered approaches that leverage collaborative intelligence between humans and AI, ensuring projects deliver exactly what's needed while reducing costs."
  order: 3

